export const products = [
    {
        id: 0,
        slug: '0',
        name: 'Lorem ipsum lorem iprem ipsum lorem i 0',
        category: '0',
        image: '/images/20.jpg',
        price: 0,
        rating: 0,
        numReview: 0,
        countInStock: 0,
        brand: '0',
        description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 1"
    },
    {
        id: 1,
        slug: '1',
        name: 'Lorem ipsum lorem iprem ipsum lorem i 1',
        category: '1',
        image: '/images/1.jpg',
        price: 1,
        rating: 1,
        numReview: 1,
        countInStock: 1,
        brand: '1',
        description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 1"
    },
    {
        id: 2,
        slug: '2',
        name: 'Lorem ipsum lorem iprem ipsum lorem i 2',
        category: '2',
        image: '/images/2.jpg',
        price: 2,
        rating: 2,
        numReview: 2,
        countInStock: 2,
        brand: '2',
        description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 2"
    },
    {
        id: 3,
        slug: '3',
        name: 'Lorem ipsum lorem iprem ipsum lorem i 3',
        category: '3',
        image: '/images/3.jpg',
        price: 3,
        rating: 3,
        numReview: 3,
        countInStock: 3,
        brand: '3',
        description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 3"
    },
    {
        id: 4,
        slug: '4',
        name: 'Lorem ipsum lorem iprem ipsum lorem i 4',
        category: '4',
        image: '/images/4.jpg',
        price: 4,
        rating: 4,
        numReview: 4,
        countInStock: 4,
        brand: '4',
        description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 4"
    },
    {
        id: 5,
        slug: '5',
        name: 'Lorem ipsum lorem iprem ipsum lorem i 5',
        category: '5',
        image: '/images/5.jpg',
        price: 5,
        rating: 5,
        numReview: 5,
        countInStock: 5,
        brand: '5',
        description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 5"
    },
    {
        id: 6,
        slug: '6',
        name: 'Lorem ipsum lorem iprem ipsum lorem i 6',
        category: '6',
        image: '/images/6.jpg',
        price: 6,
        rating: 6,
        numReview: 6,
        countInStock: 6,
        brand: '6',
        description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 6"
    },
    {
        id: 7,
        slug: '7',
        name: 'Lorem ipsum lorem iprem ipsum lorem i 7',
        category: '7',
        image: '/images/7.jpg',
        price: 7,
        rating: 7,
        numReview: 7,
        countInStock: 7,
        brand: '7',
        description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 7"
    },
    {
        id: 8,
        slug: '8',
        name: 'Lorem ipsum lorem iprem ipsum lorem i 8',
        category: '8',
        image: '/images/8.jpg',
        price: 8,
        rating: 8,
        numReview: 8,
        countInStock: 8,
        brand: '8',
        description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 8"
    },
    {
        id: 9,
        slug: '9',
        name: 'Lorem ipsum lorem iprem ipsum lorem i 9',
        category: '9',
        image: '/images/9.jpg',
        price: 9,
        rating: 9,
        numReview: 9,
        countInStock: 9,
        brand: '9',
        description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 9"
    },
    {
        id: 10,
        slug: '10',
        name: 'Lorem ipsum lorem iprem ipsum lorem i 10',
        category: '10',
        image: '/images/10.jpg',
        price: 10,
        rating: 10,
        numReview: 10,
        countInStock: 10,
        brand: '10',
        description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 10"
    },
    {
        id: 11,
        slug: '11',
        name: 'Lorem ipsum lorem iprem ipsum lorem i 11',
        category: '11',
        image: '/images/11.jpg',
        price: 11,
        rating: 11,
        numReview: 11,
        countInStock: 11,
        brand: '11',
        description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 11"
    },
    {
        id: 12,
        slug: '12',
        name: 'Lorem ipsum lorem iprem ipsum lorem i 12',
        category: '12',
        image: '/images/12.jpg',
        price: 12,
        rating: 12,
        numReview: 12,
        countInStock: 12,
        brand: '12',
        description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 12"
    },
    {
        id: 13,
        slug: '13',
        name: 'Lorem ipsum lorem iprem ipsum lorem i 13',
        category: '13',
        image: '/images/13.jpg',
        price: 13,
        rating: 13,
        numReview: 13,
        countInStock: 13,
        brand: '13',
        description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 13"
    },
    {
        id: 14,
        slug: '14',
        name: 'Lorem ipsum lorem iprem ipsum lorem i 14',
        category: '14',
        image: '/images/14.jpg',
        price: 14,
        rating: 14,
        numReview: 14,
        countInStock: 14,
        brand: '14',
        description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 14"
    },
    {
        id: 15,
        slug: '15',
        name: 'Lorem ipsum lorem iprem ipsum lorem i 15',
        category: '15',
        image: '/images/15.jpg',
        price: 15,
        rating: 15,
        numReview: 15,
        countInStock: 15,
        brand: '15',
        description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 15"
    },
    {
        id: 16,
        slug: '16',
        name: 'Lorem ipsum lorem iprem ipsum lorem i 16',
        category: '16',
        image: '/images/16.jpg',
        price: 16,
        rating: 16,
        numReview: 16,
        countInStock: 16,
        brand: '16',
        description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 16"
    },
    {
        id: 17,
        slug: '17',
        name: 'Lorem ipsum lorem iprem ipsum lorem i 17',
        category: '17',
        image: '/images/17.jpg',
        price: 17,
        rating: 17,
        numReview: 17,
        countInStock: 17,
        brand: '17',
        description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 17"
    },
    {
        id: 18,
        slug: '18',
        name: 'Lorem ipsum lorem iprem ipsum lorem i 18',
        category: '18',
        image: '/images/18.jpg',
        price: 18,
        rating: 18,
        numReview: 18,
        countInStock: 18,
        brand: '18',
        description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 18"
    },
    {
        id: 19,
        slug: '19',
        name: 'Lorem ipsum lorem iprem ipsum lorem i 19',
        category: '19',
        image: '/images/19.jpg',
        price: 19,
        rating: 19,
        numReview: 19,
        countInStock: 19,
        brand: '19',
        description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 19"
    },
    {
        id: 20,
        slug: '20',
        name: 'Lorem ipsum lorem iprem ipsum lorem i 20',
        category: '20',
        image: '/images/20.jpg',
        price: 20,
        rating: 20,
        numReview: 20,
        countInStock: 20,
        brand: '20',
        description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 20"
    },
]